import React from 'react'
import Head from 'next/head'
import Link from 'next/link'

const Layout = ({children}) => {
    
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='d-flex justify-content-between w-75 m-auto mt-2'>
            <Link href='/actor'><a className='text-decoration-none mb-2 '>Click here to add Actor &rarr;</a></Link>
            <Link href='/actorslist'><a className='text-decoration-none mb-2'>Click here to see Actors List &rarr;</a></Link>
            </div>
            {children}
          
        </div>
    )
}

export default Layout
